### ISSUE TITLE
你好啊，我发现个问题

### ISSUE THREAD

**Issue by 459737087** [quqixun/ReadWiki-ZH#1]
就是在转换的过程中，表格就被删了，留下的是空格
然后就是参考资料这一部分有的就没有了

**Comment by quqixun** [comment]
@459737087 
这个是好久之前写的了，已经不记得细节了。
表格应该是比较难转换，所以就没写。
参考资料忘记为什么没写了。😅

**Comment by 459737087** [comment]
好吧。。。
